export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_INSTRUMENTS_STATE_CHANGE = "USER_INSTRUMENTS_STATE_CHANGE";
export const USER_RAWTIMESTAMP_STATE_CHANGE = "USER_RAWTIMESTAMP_STATE_CHANGE";
export const USER_RECORDINGS_STATE_CHANGE = "USER_RECORDINGS_STATE_CHANGE";
